"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowLeft,BookOpen,Loader2,Save } from "lucide-react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";
type Student={id:string;admission_number:string;profile_id:string};type Subject={id:string;name:string;code:string;max_marks:number|null};type Exam={id:string;name:string;exam_date:string|null};
export default function AdminMarksPage(){
 const router=useRouter();const[students,setStudents]=useState<Student[]>([]);const[profiles,setProfiles]=useState<Record<string,string>>({});const[subjects,setSubjects]=useState<Subject[]>([]);const[exams,setExams]=useState<Exam[]>([]);const[examId,setExamId]=useState("");const[subjectId,setSubjectId]=useState("");const[values,setValues]=useState<Record<string,string>>({});const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
 async function load(){const{data:{session}}=await supabase.auth.getSession();if(!session?.user){router.replace("/login");return;}const{data:p}=await supabase.from("profiles").select("role").eq("id",session.user.id).single();if(!p||!["admin","principal","faculty"].includes(p.role)){await supabase.auth.signOut();router.replace("/login");return;}const[a,b,c]=await Promise.all([supabase.from("students").select("id,admission_number,profile_id").eq("status","active").order("admission_number"),supabase.from("subjects").select("id,name,code,max_marks").order("code"),supabase.from("exams").select("id,name,exam_date").order("exam_date",{ascending:false})]);const st=a.data??[];setStudents(st);setSubjects(b.data??[]);setExams(c.data??[]);const ids=st.map(x=>x.profile_id);if(ids.length){const{data:ps}=await supabase.from("profiles").select("id,full_name").in("id",ids);const m:Record<string,string>={};ps?.forEach(x=>m[x.id]=x.full_name);setProfiles(m)}setLoading(false)}
 useEffect(()=>{load()},[router]);
 async function existing(){if(!examId||!subjectId)return;const{data}=await supabase.from("marks").select("student_id,marks").eq("exam_id",examId).eq("subject_id",subjectId);const m:Record<string,string>={};(data??[]).forEach(x=>m[x.student_id]=String(x.marks));setValues(m)}
 useEffect(()=>{existing()},[examId,subjectId]);
 async function save(){if(!examId||!subjectId){setMessage("Select an exam and subject.");return;}const max=subjects.find(x=>x.id===subjectId)?.max_marks??0;if(!max){setMessage("Set max marks for this subject first.");return;}setSaving(true);const{data:{user}}=await supabase.auth.getUser();const rows=students.filter(s=>values[s.id]!==undefined&&values[s.id]!=="").map(s=>({exam_id:examId,student_id:s.id,subject_id:subjectId,marks:Number(values[s.id]),max_marks:max,entered_by:user?.id}));if(rows.some(x=>x.marks<0||x.marks>x.max_marks)){setMessage("Marks must be between 0 and the subject max marks.");setSaving(false);return;}if(!rows.length){setMessage("Enter at least one mark.");setSaving(false);return;}const{error}=await supabase.from("marks").upsert(rows,{onConflict:"exam_id,student_id,subject_id"});setMessage(error?"Error: "+error.message:"Marks saved successfully.");setSaving(false)}
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center gap-3 px-5 py-4"><Link href="/admin" className="rounded-lg p-2 hover:bg-slate-100"><ArrowLeft size={18}/></Link><BookOpen className="text-blue-700"/><h1 className="font-black text-[#102a43]">Marks Entry</h1></div></header><div className="mx-auto max-w-7xl px-5 py-8"><section className="rounded-2xl border bg-white p-6"><div className="grid gap-3 md:grid-cols-2"><select value={examId} onChange={e=>setExamId(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">Select exam</option>{exams.map(x=><option key={x.id} value={x.id}>{x.name}{x.exam_date?" — "+x.exam_date:""}</option>)}</select><select value={subjectId} onChange={e=>setSubjectId(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">Select subject</option>{subjects.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}{x.max_marks?" (Max "+x.max_marks+")":""}</option>)}</select></div></section><div className="mt-5 overflow-hidden rounded-2xl border bg-white">{loading?<div className="flex justify-center py-16"><Loader2 className="animate-spin text-blue-700"/></div>:students.length?students.map(s=><div key={s.id} className="grid grid-cols-[1fr_120px] items-center gap-4 border-b px-5 py-4"><div><p className="font-bold">{profiles[s.profile_id]??"Student"}</p><p className="text-xs text-slate-500">{s.admission_number}</p></div><input type="number" min="0" max={subjects.find(x=>x.id===subjectId)?.max_marks??undefined} step="0.01" value={values[s.id]??""} onChange={e=>setValues(v=>({...v,[s.id]:e.target.value}))} className="rounded-lg border px-3 py-2 text-right"/></div>):<p className="p-10 text-center text-sm text-slate-500">No active students found.</p>}</div>{message&&<p className="mt-4 text-sm text-slate-600">{message}</p>}<button onClick={save} disabled={saving||loading} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-blue-700 px-5 py-3 font-bold text-white disabled:opacity-50"><Save size={17}/>{saving?"Saving...":"Save Marks"}</button></div></main>
}