"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowLeft, BookOpen, Loader2, Plus, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Course={id:string;code:string;name:string};type Subject={id:string;code:string;name:string;course_id:string;max_marks:number|null};
export default function SubjectsPage(){
 const router=useRouter();const[rows,setRows]=useState<Subject[]>([]);const[courses,setCourses]=useState<Course[]>([]);const[courseId,setCourseId]=useState("");const[code,setCode]=useState("");const[name,setName]=useState("");const[max,setMax]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
 async function load(){const{data:{session}}=await supabase.auth.getSession();if(!session?.user){router.replace("/login");return;}const{data:p}=await supabase.from("profiles").select("role").eq("id",session.user.id).single();if(!p||!["admin","principal"].includes(p.role)){await supabase.auth.signOut();router.replace("/login");return;}const[a,b]=await Promise.all([supabase.from("courses").select("id,code,name").order("code"),supabase.from("subjects").select("id,code,name,course_id,max_marks").order("code")]);setCourses(a.data??[]);setRows(b.data??[]);setLoading(false)}
 useEffect(()=>{load()},[router]);
 async function add(e:React.FormEvent){e.preventDefault();if(!courseId)return;setError("");setSaving(true);const{data:p}=await supabase.from("profiles").select("college_id").eq("id",(await supabase.auth.getUser()).data.user?.id??"").single();const{error}=await supabase.from("subjects").insert({college_id:p?.college_id,course_id:courseId,code,name,max_marks:max?Number(max):null});if(error)setError(error.message);else{setCode("");setName("");setMax("");await load()}setSaving(false)}
 async function remove(id:string){if(!confirm("Delete this subject?"))return;const{error}=await supabase.from("subjects").delete().eq("id",id);if(error)setError(error.message);else load()}
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center gap-3 px-5 py-4"><Link href="/admin" className="rounded-lg p-2 hover:bg-slate-100"><ArrowLeft size={18}/></Link><BookOpen className="text-blue-700"/><h1 className="font-black text-[#102a43]">Subjects</h1></div></header><div className="mx-auto max-w-6xl px-5 py-8">
 <form onSubmit={add} className="rounded-2xl border bg-white p-6"><h2 className="font-black">Add subject</h2><div className="mt-4 grid gap-3 md:grid-cols-4"><select required value={courseId} onChange={e=>setCourseId(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">Course</option>{courses.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select><input required value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="MATH" className="rounded-xl border px-4 py-3 outline-none"/><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Mathematics" className="rounded-xl border px-4 py-3 outline-none"/><input type="number" min="1" value={max} onChange={e=>setMax(e.target.value)} placeholder="Max marks" className="rounded-xl border px-4 py-3 outline-none"/></div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<button disabled={saving} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-blue-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-50"><Plus size={16}/>{saving?"Saving...":"Add Subject"}</button></form>
 <div className="mt-6 overflow-hidden rounded-2xl border bg-white">{loading?<div className="flex justify-center py-16"><Loader2 className="animate-spin text-blue-700"/></div>:rows.length?<table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Course</th><th className="px-5 py-3">Code</th><th className="px-5 py-3">Subject</th><th className="px-5 py-3">Max Marks</th><th></th></tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id}><td className="px-5 py-4 font-bold">{courses.find(x=>x.id===r.course_id)?.code??"—"}</td><td className="px-5 py-4">{r.code}</td><td className="px-5 py-4">{r.name}</td><td className="px-5 py-4">{r.max_marks??"—"}</td><td className="px-5 py-4 text-right"><button onClick={()=>remove(r.id)} className="text-red-600"><Trash2 size={17}/></button></td></tr>)}</tbody></table>:<p className="p-10 text-center text-sm text-slate-500">No subjects configured.</p>}</div></div></main>
}
