"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Link2, Loader2, Plus, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Faculty={id:string;employee_number:string;profile_id:string}; type Profile={id:string;full_name:string}; type Course={id:string;code:string}; type Section={id:string;name:string;year_level:number;course_id:string}; type Subject={id:string;code:string;name:string;course_id:string}; type Assignment={id:string;faculty_id:string;section_id:string;subject_id:string};
export default function FacultyAssignmentsPage(){
 const router=useRouter(); const[faculty,setFaculty]=useState<Faculty[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[courses,setCourses]=useState<Course[]>([]),[sections,setSections]=useState<Section[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[rows,setRows]=useState<Assignment[]>([]); const[fid,setFid]=useState(""),[sid,setSid]=useState(""),[subid,setSubid]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const section=sections.find(x=>x.id===sid); const filtered=useMemo(()=>subjects.filter(x=>x.course_id===section?.course_id),[subjects,section]);
 async function load(){const{data:{session}}=await supabase.auth.getSession();if(!session){router.replace("/login");return;}const{data:p}=await supabase.from("profiles").select("role").eq("id",session.user.id).single();if(!p||!["admin","principal"].includes(p.role)){await supabase.auth.signOut();router.replace("/login");return;}const[a,b,c,d,e,f]=await Promise.all([supabase.from("faculty").select("id,employee_number,profile_id").eq("status","active").order("employee_number"),supabase.from("profiles").select("id,full_name").order("full_name"),supabase.from("courses").select("id,code").order("code"),supabase.from("sections").select("id,name,year_level,course_id").order("name"),supabase.from("subjects").select("id,code,name,course_id").order("code"),supabase.from("faculty_assignments").select("id,faculty_id,section_id,subject_id").order("created_at",{ascending:false})]);setFaculty(a.data??[]);setProfiles(b.data??[]);setCourses(c.data??[]);setSections(d.data??[]);setSubjects(e.data??[]);setRows(f.data??[]);if(f.error)setError(f.error.message);setLoading(false)} useEffect(()=>{load()},[router]);
 const fname=(id:string)=>{const f=faculty.find(x=>x.id===id);return profiles.find(x=>x.id===f?.profile_id)?.full_name??f?.employee_number??"—"}; const slabel=(id:string)=>{const s=sections.find(x=>x.id===id);const c=courses.find(x=>x.id===s?.course_id);return s?`${c?.code??"Course"} · ${s.year_level===1?"1st":"2nd"} Year · ${s.name}`:"—"}; const sublabel=(id:string)=>{const s=subjects.find(x=>x.id===id);return s?`${s.code} — ${s.name}`:"—"};
 async function add(e:React.FormEvent){e.preventDefault();setError("");setSaving(true);const{data:{user}}=await supabase.auth.getUser();const{data:p}=await supabase.from("profiles").select("college_id").eq("id",user?.id??"").single();if(!p?.college_id){setError("Your admin account is not linked to a college yet.");setSaving(false);return;}const{error}=await supabase.from("faculty_assignments").insert({college_id:p.college_id,faculty_id:fid,section_id:sid,subject_id:subid});if(error)setError(error.code==="23505"?"This assignment already exists.":error.message);else{setFid("");setSid("");setSubid("");await load()}setSaving(false)}
 async function remove(id:string){if(!confirm("Remove this faculty assignment?"))return;const{error}=await supabase.from("faculty_assignments").delete().eq("id",id);if(error)setError(error.message);else await load()}
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center gap-3 px-5 py-4"><Link href="/admin" className="rounded-lg p-2 hover:bg-slate-100"><ArrowLeft size={18}/></Link><Link2 className="text-blue-700"/><div><h1 className="font-black text-[#102a43]">Faculty Assignments</h1><p className="text-xs text-slate-500">Assign faculty to sections and subjects.</p></div></div></header><div className="mx-auto max-w-6xl px-5 py-8"><form onSubmit={add} className="rounded-2xl border bg-white p-6"><h2 className="font-black">Add assignment</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><select required value={fid} onChange={e=>setFid(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">Select faculty</option>{faculty.map(f=><option key={f.id} value={f.id}>{fname(f.id)} · {f.employee_number}</option>)}</select><select required value={sid} onChange={e=>{setSid(e.target.value);setSubid("")}} className="rounded-xl border px-4 py-3"><option value="">Select section</option>{sections.map(s=>{const c=courses.find(x=>x.id===s.course_id);return <option key={s.id} value={s.id}>{c?.code??"Course"} · {s.year_level===1?"1st":"2nd"} Year · {s.name}</option>})}</select><select required value={subid} onChange={e=>setSubid(e.target.value)} disabled={!sid} className="rounded-xl border px-4 py-3 disabled:bg-slate-100"><option value="">{sid?"Select subject":"Select section first"}</option>{filtered.map(s=><option key={s.id} value={s.id}>{s.code} — {s.name}</option>)}</select></div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<button disabled={saving} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-blue-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-50"><Plus size={16}/>{saving?"Saving...":"Assign Faculty"}</button></form><div className="mt-6 overflow-hidden rounded-2xl border bg-white">{loading?<div className="flex justify-center py-16"><Loader2 className="animate-spin text-blue-700"/></div>:rows.length?<table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Faculty</th><th className="px-5 py-3">Section</th><th className="px-5 py-3">Subject</th><th></th></tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id}><td className="px-5 py-4 font-bold">{fname(r.faculty_id)}</td><td className="px-5 py-4">{slabel(r.section_id)}</td><td className="px-5 py-4">{sublabel(r.subject_id)}</td><td className="px-5 py-4 text-right"><button onClick={()=>remove(r.id)} className="text-red-600"><Trash2 size={17}/></button></td></tr>)}</tbody></table>:<p className="p-10 text-center text-sm text-slate-500">No faculty assignments configured.</p>}</div></div></main>
}