"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowLeft,ClipboardCheck,Loader2,Save } from "lucide-react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Student={id:string;admission_number:string;profile_id:string};
type Subject={id:string;name:string;code:string};
export default function AdminAttendancePage(){
 const router=useRouter();const[students,setStudents]=useState<Student[]>([]);const[profiles,setProfiles]=useState<Record<string,string>>({});const[subjects,setSubjects]=useState<Subject[]>([]);const[subjectId,setSubjectId]=useState("");const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[status,setStatus]=useState<Record<string,string>>({});const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
 async function load(){const{data:{session}}=await supabase.auth.getSession();if(!session?.user){router.replace("/login");return;}const{data:p}=await supabase.from("profiles").select("role").eq("id",session.user.id).single();if(!p||!["admin","principal","faculty"].includes(p.role)){await supabase.auth.signOut();router.replace("/login");return;}const[a,b]=await Promise.all([supabase.from("students").select("id,admission_number,profile_id").eq("status","active").order("admission_number"),supabase.from("subjects").select("id,name,code").order("code")]);const st=a.data??[];setStudents(st);setSubjects(b.data??[]);const ids=st.map(x=>x.profile_id);if(ids.length){const{data:ps}=await supabase.from("profiles").select("id,full_name").in("id",ids);const m:Record<string,string>={};ps?.forEach(x=>m[x.id]=x.full_name);setProfiles(m)}setLoading(false)}
 useEffect(()=>{load()},[router]);
 async function existing(){if(!subjectId||!date)return;const{data}=await supabase.from("attendance").select("student_id,status").eq("subject_id",subjectId).eq("attendance_date",date);const m:Record<string,string>={};(data??[]).forEach(x=>m[x.student_id]=x.status);setStatus(m)}
 useEffect(()=>{existing()},[subjectId,date]);
 async function save(){if(!subjectId||!date){setMessage("Select a subject and date.");return;}setSaving(true);setMessage("");const{data:{user}}=await supabase.auth.getUser();const rows=students.filter(s=>status[s.id]).map(s=>({student_id:s.id,subject_id:subjectId,attendance_date:date,status:status[s.id],marked_by:user?.id}));if(!rows.length){setMessage("Mark at least one student.");setSaving(false);return;}const{error}=await supabase.from("attendance").upsert(rows,{onConflict:"student_id,subject_id,attendance_date"});setMessage(error?"Error: "+error.message:"Attendance saved successfully.");setSaving(false)}
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center gap-3 px-5 py-4"><Link href="/admin" className="rounded-lg p-2 hover:bg-slate-100"><ArrowLeft size={18}/></Link><ClipboardCheck className="text-blue-700"/><h1 className="font-black text-[#102a43]">Attendance Entry</h1></div></header><div className="mx-auto max-w-7xl px-5 py-8"><section className="rounded-2xl border bg-white p-6"><div className="grid gap-3 md:grid-cols-2"><select value={subjectId} onChange={e=>setSubjectId(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">Select subject</option>{subjects.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-xl border px-4 py-3"/></div></section><div className="mt-5 overflow-hidden rounded-2xl border bg-white">{loading?<div className="flex justify-center py-16"><Loader2 className="animate-spin text-blue-700"/></div>:students.length?<div>{students.map(s=><div key={s.id} className="grid grid-cols-[1fr_auto] items-center gap-4 border-b px-5 py-4"><div><p className="font-bold">{profiles[s.profile_id]??"Student"}</p><p className="text-xs text-slate-500">{s.admission_number}</p></div><select value={status[s.id]??""} onChange={e=>setStatus(v=>({...v,[s.id]:e.target.value}))} className="rounded-lg border px-3 py-2 text-sm"><option value="">Not marked</option><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option><option value="excused">Excused</option></select></div>)}</div>:<p className="p-10 text-center text-sm text-slate-500">No active students found.</p>}</div>{message&&<p className="mt-4 text-sm text-slate-600">{message}</p>}<button onClick={save} disabled={saving||loading} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-blue-700 px-5 py-3 font-bold text-white disabled:opacity-50"><Save size={17}/>{saving?"Saving...":"Save Attendance"}</button></div></main>
}