"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowLeft, Loader2, Plus, Trash2, LayoutDashboard } from "lucide-react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Year={id:string;name:string};type Course={id:string;code:string;name:string};type Section={id:string;name:string;year_level:number;academic_year_id:string;course_id:string};
export default function SectionsPage(){
 const router=useRouter();const[rows,setRows]=useState<Section[]>([]);const[years,setYears]=useState<Year[]>([]);const[courses,setCourses]=useState<Course[]>([]);const[yearId,setYearId]=useState("");const[courseId,setCourseId]=useState("");const[name,setName]=useState("");const[level,setLevel]=useState("1");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
 async function load(){const{data:{session}}=await supabase.auth.getSession();if(!session?.user){router.replace("/login");return;}const{data:p}=await supabase.from("profiles").select("role").eq("id",session.user.id).single();if(!p||!["admin","principal"].includes(p.role)){await supabase.auth.signOut();router.replace("/login");return;}const[a,b,c]=await Promise.all([supabase.from("academic_years").select("id,name").order("name",{ascending:false}),supabase.from("courses").select("id,code,name").order("code"),supabase.from("sections").select("id,name,year_level,academic_year_id,course_id").order("name")]);setYears(a.data??[]);setCourses(b.data??[]);setRows(c.data??[]);setLoading(false)}
 useEffect(()=>{load()},[router]);
 async function add(e:React.FormEvent){e.preventDefault();if(!yearId||!courseId)return;setError("");setSaving(true);const{data:p}=await supabase.from("profiles").select("college_id").eq("id",(await supabase.auth.getUser()).data.user?.id??"").single();const{error}=await supabase.from("sections").insert({college_id:p?.college_id,academic_year_id:yearId,course_id:courseId,name,year_level:Number(level)});if(error)setError(error.message);else{setName("");await load()}setSaving(false)}
 async function remove(id:string){if(!confirm("Delete this section?"))return;const{error}=await supabase.from("sections").delete().eq("id",id);if(error)setError(error.message);else load()}
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center gap-3 px-5 py-4"><Link href="/admin" className="rounded-lg p-2 hover:bg-slate-100"><ArrowLeft size={18}/></Link><LayoutDashboard className="text-blue-700"/><h1 className="font-black text-[#102a43]">Sections</h1></div></header><div className="mx-auto max-w-6xl px-5 py-8">
 <form onSubmit={add} className="rounded-2xl border bg-white p-6"><h2 className="font-black">Add section</h2><div className="mt-4 grid gap-3 md:grid-cols-4"><select required value={yearId} onChange={e=>setYearId(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">Academic year</option>{years.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select required value={courseId} onChange={e=>setCourseId(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">Course</option>{courses.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select><select value={level} onChange={e=>setLevel(e.target.value)} className="rounded-xl border px-4 py-3"><option value="1">1st Year</option><option value="2">2nd Year</option></select><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Section A" className="rounded-xl border px-4 py-3 outline-none"/></div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<button disabled={saving} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-blue-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-50"><Plus size={16}/>{saving?"Saving...":"Add Section"}</button></form>
 <div className="mt-6 overflow-hidden rounded-2xl border bg-white">{loading?<div className="flex justify-center py-16"><Loader2 className="animate-spin text-blue-700"/></div>:rows.length?<table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Year</th><th className="px-5 py-3">Course</th><th className="px-5 py-3">Year Level</th><th className="px-5 py-3">Section</th><th></th></tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id}><td className="px-5 py-4">{years.find(x=>x.id===r.academic_year_id)?.name??"—"}</td><td className="px-5 py-4 font-bold">{courses.find(x=>x.id===r.course_id)?.code??"—"}</td><td className="px-5 py-4">{r.year_level===1?"1st":"2nd"}</td><td className="px-5 py-4">{r.name}</td><td className="px-5 py-4 text-right"><button onClick={()=>remove(r.id)} className="text-red-600"><Trash2 size={17}/></button></td></tr>)}</tbody></table>:<p className="p-10 text-center text-sm text-slate-500">No sections configured.</p>}</div></div></main>
}
