"use client";

import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

type Section={id:string;name:string;year_level:number};
type Subject={id:string;name:string;code:string};
type Student={id:string;admission_number:string;profile_id:string};

export default function FacultyAttendancePage(){
 const[sections,setSections]=useState<Section[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[students,setStudents]=useState<Student[]>([]),[names,setNames]=useState<Record<string,string>>({}),[sectionId,setSectionId]=useState(""),[subjectId,setSubjectId]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[status,setStatus]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/login";return}const{data:p}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(!p||p.role!=="faculty"){await supabase.auth.signOut();window.location.href="/login";return}const{data:f}=await supabase.from("faculty").select("id").eq("profile_id",user.id).single();if(!f){setLoading(false);return}const{data:a}=await supabase.from("faculty_assignments").select("section_id,subject_id").eq("faculty_id",f.id);const sids=[...new Set((a??[]).map(x=>x.section_id))],subs=[...new Set((a??[]).map(x=>x.subject_id))];const[s,u]=await Promise.all([sids.length?supabase.from("sections").select("id,name,year_level").in("id",sids).order("name"):Promise.resolve({data:[]}),subs.length?supabase.from("subjects").select("id,name,code").in("id",subs).order("code"):Promise.resolve({data:[]})]);setSections(s.data??[]);setSubjects(u.data??[]);setLoading(false)})()},[]);
 useEffect(()=>{(async()=>{if(!sectionId){setStudents([]);return}const{data}=await supabase.from("students").select("id,admission_number,profile_id").eq("section_id",sectionId).eq("status","active").order("admission_number");const rows=data??[];setStudents(rows);const{data:p}=await supabase.from("profiles").select("id,full_name").in("id",rows.map(x=>x.profile_id));const m:Record<string,string>={};p?.forEach(x=>m[x.id]=x.full_name);setNames(m)})()},[sectionId]);
 useEffect(()=>{(async()=>{if(!sectionId||!subjectId||!date||!students.length){setStatus({});return}const{data}=await supabase.from("attendance").select("student_id,status").eq("subject_id",subjectId).eq("attendance_date",date).in("student_id",students.map(s=>s.id));const m:Record<string,string>={};data?.forEach(x=>m[x.student_id]=x.status);setStatus(m)})()},[sectionId,subjectId,date,students]);
 async function save(){if(!sectionId||!subjectId){setMessage("Select section and subject.");return}const rows=students.filter(s=>status[s.id]).map(s=>({student_id:s.id,subject_id:subjectId,attendance_date:date,status:status[s.id],marked_by:undefined}));if(!rows.length){setMessage("Mark at least one student.");return}setSaving(true);const{data:{user}}=await supabase.auth.getUser();rows.forEach(x=>x.marked_by=user?.id);const{error}=await supabase.from("attendance").upsert(rows,{onConflict:"student_id,subject_id,attendance_date"});setMessage(error?"Error: "+error.message:"Attendance saved successfully.");setSaving(false)}
 return <main className="min-h-screen bg-slate-950 text-white"><div className="mx-auto max-w-6xl px-6 py-8"><a href="/faculty" className="text-sm text-sky-400">← Faculty Dashboard</a><h1 className="mt-3 text-3xl font-bold">Attendance</h1><p className="mt-2 text-slate-400">Only assigned section and subject combinations are available.</p><div className="mt-7 grid gap-3 md:grid-cols-3"><select value={sectionId} onChange={e=>{setSectionId(e.target.value);setSubjectId("")}} className="rounded-xl border border-white/10 bg-slate-900 px-4 py-3"><option value="">Select section</option>{sections.map(s=><option key={s.id} value={s.id}>{s.name} • Year {s.year_level}</option>)}</select><select value={subjectId} onChange={e=>setSubjectId(e.target.value)} disabled={!sectionId} className="rounded-xl border border-white/10 bg-slate-900 px-4 py-3 disabled:opacity-50"><option value="">Select subject</option>{subjects.filter(s=>{const sec=sections.find(x=>x.id===sectionId);return sec?true:false}).map(s=><option key={s.id} value={s.id}>{s.code} — {s.name}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-xl border border-white/10 bg-slate-900 px-4 py-3"/></div><div className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-white/5">{loading?<p className="p-8 text-slate-400">Loading...</p>:!sectionId?<p className="p-8 text-slate-400">Select a section to load students.</p>:students.map(s=><div key={s.id} className="grid grid-cols-[1fr_auto] items-center gap-4 border-b border-white/10 px-5 py-4"><div><p className="font-semibold">{names[s.profile_id]||"Student"}</p><p className="text-xs text-slate-400">{s.admission_number}</p></div><select value={status[s.id]||""} onChange={e=>setStatus(v=>({...v,[s.id]:e.target.value}))} className="rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-sm"><option value="">Not marked</option><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option><option value="excused">Excused</option></select></div>)}{!loading&&sectionId&&!students.length&&<p className="p-8 text-slate-400">No active students in this section.</p>}</div>{message&&<p className="mt-4 text-sm text-slate-300">{message}</p>}<button onClick={save} disabled={saving||loading||!sectionId||!subjectId} className="mt-5 rounded-xl bg-sky-500 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{saving?"Saving...":"Save Attendance"}</button></div></main>
}