"use client";

import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { ArrowLeft, IndianRupee, Loader2, Save, Search } from "lucide-react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Student={id:string;admission_number:string;profile_id:string};
type Fee={id:string;student_id:string;academic_year_id:string;fee_type:string;amount:number;paid_amount:number;status:string;due_date:string|null;paid_at:string|null};

export default function AdminFeesPage(){
 const router=useRouter();const[students,setStudents]=useState<Student[]>([]);const[profiles,setProfiles]=useState<Record<string,string>>({});const[rows,setRows]=useState<Fee[]>([]);
 const[studentId,setStudentId]=useState("");const[feeType,setFeeType]=useState("");const[amount,setAmount]=useState("");const[due,setDue]=useState("");
 const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[search,setSearch]=useState("");const[editing,setEditing]=useState<Fee|null>(null);const[editPaid,setEditPaid]=useState("");const[editStatus,setEditStatus]=useState("pending");
 async function load(){
  const{data:{session}}=await supabase.auth.getSession();if(!session?.user){router.replace("/login");return}
  const{data:p}=await supabase.from("profiles").select("role,is_active").eq("id",session.user.id).single();if(!p||!["admin","principal"].includes(p.role)||p.is_active===false){await supabase.auth.signOut();router.replace("/login");return}
  const[a,b]=await Promise.all([supabase.from("students").select("id,admission_number,profile_id").eq("status","active").order("admission_number"),supabase.from("fees").select("id,student_id,academic_year_id,fee_type,amount,paid_amount,status,due_date,paid_at").order("due_date",{ascending:true,nullsFirst:false})]);
  setStudents(a.data??[]);setRows(b.data??[]);const ids=(a.data??[]).map(x=>x.profile_id);if(ids.length){const{data:ps}=await supabase.from("profiles").select("id,full_name").in("id",ids);const m:Record<string,string>={};ps?.forEach(x=>m[x.id]=x.full_name);setProfiles(m)}setLoading(false)
 }
 useEffect(()=>{load()},[router]);
 async function add(e:React.FormEvent){e.preventDefault();setError("");setSaving(true);const{data:{user}}=await supabase.auth.getUser();const{data:p}=await supabase.from("profiles").select("college_id").eq("id",user?.id??"").single();if(!p?.college_id){setError("Your account is not linked to a college.");setSaving(false);return}const{data:student}=await supabase.from("students").select("academic_year_id,college_id").eq("id",studentId).single();if(!student||student.college_id!==p.college_id){setError("Student not found in your college.");setSaving(false);return}const n=Number(amount);if(!feeType.trim()||!Number.isFinite(n)||n<0){setError("Enter a valid fee type and amount.");setSaving(false);return}const{error}=await supabase.from("fees").insert({student_id:studentId,academic_year_id:student.academic_year_id,fee_type:feeType.trim(),amount:n,due_date:due||null});if(error)setError(error.message);else{setFeeType("");setAmount("");setDue("");setStudentId("");await load()}setSaving(false)}
 function startEdit(row:Fee){setEditing(row);setEditPaid(String(row.paid_amount??0));setEditStatus(row.status);setError("")}
 async function saveEdit(){if(!editing)return;const paid=Number(editPaid);if(!Number.isFinite(paid)||paid<0||paid>Number(editing.amount)){setError("Paid amount must be between ₹0 and the total fee.");return}setSaving(true);setError("");let status=editStatus;if(paid===Number(editing.amount))status="paid";else if(paid>0&&status!=="waived")status="partial";else if(paid===0&&status==="paid")status="pending";const{error}=await supabase.from("fees").update({paid_amount:paid,status,paid_at:paid>0?new Date().toISOString():null}).eq("id",editing.id);if(error)setError(error.message);else{setEditing(null);await load()}setSaving(false)}
 const filtered=useMemo(()=>rows.filter(r=>{const s=students.find(x=>x.id===r.student_id);const q=search.toLowerCase();return !q||r.fee_type.toLowerCase().includes(q)||(s?.admission_number??"").toLowerCase().includes(q)||(s?profiles[s.profile_id]??"":"").toLowerCase().includes(q)}),[rows,students,profiles,search]);
 const total=rows.reduce((n,x)=>n+Number(x.amount),0),paid=rows.reduce((n,x)=>n+Number(x.paid_amount),0),balance=Math.max(total-paid,0);
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4"><div className="flex items-center gap-3"><Link href="/admin" className="rounded-lg p-2 hover:bg-slate-100"><ArrowLeft size={18}/></Link><IndianRupee className="text-blue-700"/><div><h1 className="font-black text-[#102a43]">Fee Management</h1><p className="text-xs text-slate-500">Create charges and record collections</p></div></div></div></header><div className="mx-auto max-w-7xl px-5 py-8">
 <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Billed</p><p className="mt-1 text-2xl font-black">₹{total.toLocaleString("en-IN")}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Collected</p><p className="mt-1 text-2xl font-black text-emerald-700">₹{paid.toLocaleString("en-IN")}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Balance</p><p className="mt-1 text-2xl font-black text-amber-700">₹{balance.toLocaleString("en-IN")}</p></div></div>
 <form onSubmit={add} className="mt-6 rounded-2xl border bg-white p-6"><h2 className="font-black text-[#102a43]">Add fee record</h2><div className="mt-4 grid gap-3 md:grid-cols-4"><select required value={studentId} onChange={e=>setStudentId(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">Student</option>{students.map(x=><option key={x.id} value={x.id}>{x.admission_number} — {profiles[x.profile_id]??"Student"}</option>)}</select><input required value={feeType} onChange={e=>setFeeType(e.target.value)} placeholder="Tuition Fee" className="rounded-xl border px-4 py-3 outline-none"/><input required type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount" className="rounded-xl border px-4 py-3 outline-none"/><input type="date" value={due} onChange={e=>setDue(e.target.value)} className="rounded-xl border px-4 py-3"/></div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<button disabled={saving} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-blue-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?"Saving...":"Add Fee"}</button></form>
 {editing&&<section className="mt-6 rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-black text-[#102a43]">Record Payment</h2><p className="text-sm text-slate-500">{editing.fee_type} • Total ₹{Number(editing.amount).toLocaleString("en-IN")}</p></div><button onClick={()=>setEditing(null)} className="text-sm font-bold text-slate-500">Cancel</button></div><div className="mt-4 grid gap-3 md:grid-cols-2"><input type="number" min="0" max={Number(editing.amount)} step="0.01" value={editPaid} onChange={e=>setEditPaid(e.target.value)} placeholder="Paid amount" className="rounded-xl border px-4 py-3"/><select value={editStatus} onChange={e=>setEditStatus(e.target.value)} className="rounded-xl border px-4 py-3"><option value="pending">Pending</option><option value="partial">Partial</option><option value="paid">Paid</option><option value="waived">Waived</option></select></div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<button onClick={saveEdit} disabled={saving} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-50"><Save size={16}/>{saving?"Saving...":"Save Payment"}</button></section>}
 <div className="mt-6 flex items-center gap-2 rounded-xl border bg-white px-4 py-3"><Search size={18} className="text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search student, admission number or fee type" className="w-full outline-none"/></div>
 <div className="mt-5 overflow-hidden rounded-2xl border bg-white">{loading?<div className="flex justify-center py-16"><Loader2 className="animate-spin text-blue-700"/></div>:filtered.length?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">Fee</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Paid</th><th className="px-5 py-3">Balance</th><th className="px-5 py-3">Status</th><th></th></tr></thead><tbody className="divide-y">{filtered.map(r=>{const s=students.find(x=>x.id===r.student_id);return <tr key={r.id}><td className="px-5 py-4 font-bold">{s?profiles[s.profile_id]??s.admission_number:"Student"}<span className="ml-2 text-xs font-normal text-slate-400">{s?.admission_number}</span></td><td className="px-5 py-4">{r.fee_type}</td><td className="px-5 py-4">₹{Number(r.amount).toLocaleString("en-IN")}</td><td className="px-5 py-4">₹{Number(r.paid_amount).toLocaleString("en-IN")}</td><td className="px-5 py-4">₹{Math.max(Number(r.amount)-Number(r.paid_amount),0).toLocaleString("en-IN")}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold capitalize">{r.status}</span></td><td className="px-5 py-4 text-right"><button onClick={()=>startEdit(r)} className="font-bold text-blue-700">Payment</button></td></tr>})}</tbody></table></div>:<p className="p-10 text-center text-sm text-slate-500">No fee records found.</p>}</div>
 </div></main>
}