"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowLeft, Printer, Loader2, GraduationCap } from "lucide-react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

export default function StudentIdCard(){
 const router=useRouter();const[loading,setLoading]=useState(true);const[student,setStudent]=useState<any>(null);const[name,setName]=useState("");
 useEffect(()=>{(async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session){router.replace("/login");return}const{data:p}=await supabase.from("profiles").select("full_name,role,is_active,phone").eq("id",session.user.id).single();if(!p||p.role!=="student"||p.is_active===false){await supabase.auth.signOut();router.replace("/login");return}setName(p.full_name);const{data:s}=await supabase.from("students").select("admission_number,roll_number,date_of_birth,gender,guardian_name,status,academic_year_id,section_id").eq("profile_id",session.user.id).single();setStudent(s);setLoading(false)})()},[router]);
 if(loading)return <main className="flex min-h-screen items-center justify-center bg-slate-50"><Loader2 className="animate-spin text-blue-700"/></main>;
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white print:hidden"><div className="mx-auto flex max-w-3xl items-center justify-between px-5 py-4"><Link href="/student" className="flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft size={17}/> Student Portal</Link><button onClick={()=>window.print()} className="flex items-center gap-2 rounded-xl bg-blue-700 px-4 py-2 text-sm font-bold text-white"><Printer size={16}/> Print / Save PDF</button></div></header><div className="flex min-h-[calc(100vh-70px)] items-center justify-center px-5 py-10 print:min-h-0 print:px-0"><section className="w-full max-w-md overflow-hidden rounded-3xl border bg-white shadow-xl print:rounded-2xl print:shadow-none"><div className="bg-[#102a43] p-6 text-center text-white"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-white/10"><GraduationCap size={30}/></div><p className="mt-3 text-xs font-bold uppercase tracking-[.18em] text-blue-200">Gnana Saraswati Jr. College</p><h1 className="mt-1 text-xl font-black">Student Identity Card</h1><p className="text-xs text-blue-200">Bethamcherla, Andhra Pradesh</p></div><div className="p-7"><div className="mx-auto grid h-24 w-24 place-items-center rounded-full bg-blue-50 text-3xl font-black text-blue-700">{name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><h2 className="mt-4 text-center text-xl font-black text-[#102a43]">{name}</h2><div className="mt-6 divide-y rounded-2xl border">{[["Admission Number",student?.admission_number],["Roll Number",student?.roll_number||"—"],["Gender",student?.gender||"—"],["Date of Birth",student?.date_of_birth||"—"],["Guardian",student?.guardian_name||"—"],["Status",student?.status||"—"]].map(([k,v])=><div key={k} className="flex justify-between gap-4 px-4 py-3 text-sm"><span className="text-slate-500">{k}</span><span className="font-bold text-right capitalize">{v}</span></div>)}</div><p className="mt-6 text-center text-xs text-slate-400">This card is generated from the student's current college portal record.</p></div></section></div></main>
}